<Mess1>
	BoxLayout:
		orientation :"vertical"
		Button:
			text : "close"
			size_hint: 1,.1
			on_press : root.q()
		TextInput:
			id : content
			hint_text: "noi dung"
			color : 1,0,0,1
			size_hint: 1,.7
	BoxLayout:
		TextInput:
			id : textct
			hint_text: "message"
			color : 1,0,0,1
			size_hint: .7,.2
		Button:
			text : "click"
			size_hint: .3,.2
			on_press: root.thu()
<Mess2>
	Label:
		text: "222222222"
		color : 1,0,0,1